language: node_js
node_js:
  - "node"
cache:
  directories:
    - $HOME/.cache/yarn
    - .cache
dist: trusty
os:
  - linux
script:
  - yarn test
before_deploy: rm -rf node_modules
deploy:
  provider: heroku
  api_key:
    secure: 33bfd837-24fd-4f1b-95f7-dd0ddba9bb61
  app: archanai-lab
  on:
    repo: jakkrits/ReactQL
